var wordList = [
  "3 different ways to <keyword>",
  "Why I love to go to <keyword> in the summer",
  "How <keyword> will change your life",
  "12 things you didn't know about <keyword>",
  "Get the most out of <keyword> and Facebook",
  "How much is <keyword> worth to you?",
  "How to use <keyword> to solve problems",
  "How to start a business with <keyword>",
  "The <keyword> that wins customers",
  "5 important lessons I learned about <keyword>",
  "3 different ways to <keyword>",
  "30 <keyword> quotes",
  "Why you should avoid <keyword> at all costs",
  "Why I switched from Coke to <keyword>",
  "<keyword> in 3 easy steps",
  "3 different ways to <keyword>",
  "Where to find <keyword> in your area",
  "The <keyword> that will help you sleep easy at night",
  "5 <keyword> recipes to die for",
  "<keyword> is coming. Are you prepared?",
  "10 facts about <keyword> that will blow your mind",
  "27 secrets about <keyword>",
  "How <keyword> is changing my life",
  "Save hundreds with these 18 easy <keyword> moves",
  "An apple a day will keep the <keyword> away",
  "Why you absolutely NEED <keyword> in your life",
  "Stop running from <keyword>",
  "<keyword> is the key to all of your problems",
  "6 foods you can eat to lose <keyword>",
  "Why <keyword> is more important that the air you breathe",
  "This <keyword> scientist has secrets to share",
  "25 <keyword> hacks",
  "Why you should <keyword> first thing in the morning",
  "We're living on a <keyword>",
  "Is pizza really better than <keyword>?",
  "Why I gave away all of my <keyword>",
  "Why I quit my job in order to pursue <keyword>",
  "<keyword> vs. Pilates: Which one is better for your health?",
];

var keywordList = [
  "1 <keyword>",
  "2 <keyword>",
  "3 <keyword>",
  "4 <keyword>",
  "5 <keyword>",
  "6 <keyword>",
  "7 <keyword>",
  "8 <keyword>",
  "9 <keyword>",
  "10 <keyword>",
  "11 <keyword>",
  "16 <keyword>",
  "17 <keyword>",
  "18 <keyword>",
  "19 <keyword>",
  "20 <keyword>",
  "21 <keyword>",
  "22 <keyword>",
  "23 <keyword>",
  "24 <keyword>",
  "25 <keyword>",
  "26 <keyword>",
  "27 <keyword>",
  "28 <keyword>",
  "29 <keyword>",
  "30 <keyword>",
  "31 <keyword>",
  "32 <keyword>",
  "33 <keyword>",
  "34 <keyword>",
  "35 <keyword>",
  "36 <keyword>",
  "37 <keyword>",
  "38 <keyword>",
  "39 <keyword>",
  "40 <keyword>",
  "41 <keyword>",
  "42 <keyword>",
  "43 <keyword>",
  "44 <keyword>",
  "45 <keyword>",
  "46 <keyword>",
  "47 <keyword>",
  "48 <keyword>",
  "49 <keyword>",
  "50 <keyword>",
  "51 <keyword>",
  "52 <keyword>",
  "53 <keyword>",
  "54 <keyword>",
  "55 <keyword>",
  "56 <keyword>",
  "57 <keyword>",
  "58 <keyword>",
  "59 <keyword>",
  "60 <keyword>",
];